#!/usr/bin/env python3
"""Validate the small, typed acceleration graph and emit a deterministic PX4 header."""

import argparse
import hashlib
import json
import math
from pathlib import Path


OPERATIONS = {
    "velocity_error": ((), "velocity", "VelocityError"),
    "acceleration_residual": ((), "acceleration", "AccelerationResidual"),
    "velocity_gain": (("velocity",), "acceleration", "VelocityGain"),
    "lowpass_acceleration": (("acceleration",), "acceleration", "LowpassAcceleration"),
    "acceleration_gain": (("acceleration",), "acceleration", "AccelerationGain"),
    "add_acceleration": (("acceleration", "acceleration"), "acceleration", "AddAcceleration"),
    "velocity_gate": (("velocity", "acceleration"), "acceleration", "VelocityGate"),
    "limit_acceleration": (("acceleration",), "acceleration", "LimitAcceleration"),
}


def finite_number(value, lower, upper, label):
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError(f"{label}: finite number required")
    if not lower <= value <= upper:
        raise ValueError(f"{label}: value outside [{lower}, {upper}]")
    return float(value)


def three_numbers(value, lower, upper, label):
    if not isinstance(value, list) or len(value) != 3:
        raise ValueError(f"{label}: exactly three numbers required")
    return [finite_number(number, lower, upper, label) for number in value]


def validate(spec):
    if not isinstance(spec, dict) or spec.get("schema") != 1:
        raise ValueError("unsupported candidate schema")
    nodes = spec.get("nodes")
    if not isinstance(nodes, list) or not 1 <= len(nodes) <= 16:
        raise ValueError("candidate must have 1..16 nodes")
    names = {}
    typed = []
    for index, node in enumerate(nodes):
        if not isinstance(node, dict) or not isinstance(node.get("id"), str):
            raise ValueError(f"node {index}: id required")
        name = node["id"]
        if not name.isidentifier() or name in names:
            raise ValueError(f"node {index}: invalid or duplicate id")
        op = node.get("op")
        if op not in OPERATIONS:
            raise ValueError(f"node {index}: unsupported operation")
        input_units, output_unit, _ = OPERATIONS[op]
        input_names = [] if not input_units else [node.get("input")]
        if len(input_units) == 2:
            input_names = [node.get("left"), node.get("right")]
        input_indexes = []
        for source, expected_unit in zip(input_names, input_units):
            if source not in names:
                raise ValueError(f"node {index}: input must refer to an earlier node")
            source_index, actual_unit = names[source]
            if actual_unit != expected_unit:
                raise ValueError(f"node {index}: expected {expected_unit}, got {actual_unit}")
            input_indexes.append(source_index)
        names[name] = (index, output_unit)
        x = y = z = 0.0
        if op in ("velocity_gain", "acceleration_gain"):
            x, y, z = three_numbers(node.get("gain"), -5.0, 5.0, "gain")
        elif op == "lowpass_acceleration":
            x = finite_number(node.get("tau_s"), 0.02, 5.0, "tau_s")
        elif op == "limit_acceleration":
            x, y, z = three_numbers(node.get("limit_m_s2"), 0.05, 2.0, "limit_m_s2")
        elif op == "velocity_gate":
            thresholds = node.get("threshold_m_s")
            if not isinstance(thresholds, list) or len(thresholds) != 2:
                raise ValueError("threshold_m_s: exactly two numbers required")
            x = finite_number(thresholds[0], 0.0, 3.0, "threshold_m_s")
            y = finite_number(thresholds[1], 0.0, 3.0, "threshold_m_s")
            if y <= x:
                raise ValueError("threshold_m_s: upper threshold must exceed lower threshold")
        typed.append((op, input_indexes, x, y, z))
    output = spec.get("output")
    if output not in names or names[output][1] != "acceleration":
        raise ValueError("output must be an acceleration node")
    maximum = finite_number(spec.get("maximum_correction_m_s2"), 0.05, 2.0, "maximum_correction_m_s2")
    if typed[-1][0] != "limit_acceleration" or names[output][0] != len(typed) - 1:
        raise ValueError("output must be the final limit_acceleration node")
    return typed, names[output][0], maximum


def generate(spec):
    typed, output, maximum = validate(spec)
    canonical = json.dumps(spec, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    digest = hashlib.sha256(canonical).hexdigest()
    def literal(value):
        rendered = format(value, ".9g")
        if "." not in rendered and "e" not in rendered:
            rendered += ".0"
        return rendered + "f"

    lines = [
        "// Generated by Tools/merivus/flight_control_research/candidate.py; do not edit.",
        f"// Candidate SHA-256: {digest}",
        "static constexpr Node nodes[] = {",
    ]
    for op, inputs, x, y, z in typed:
        a = inputs[0] if inputs else -1
        b = inputs[1] if len(inputs) > 1 else -1
        lines.append(f"\t{{Op::{OPERATIONS[op][2]}, {a}, {b}, {literal(x)}, {literal(y)}, {literal(z)}}},")
    lines += [
        "};",
        f"static constexpr unsigned node_count = {len(typed)};",
        f"static constexpr unsigned output_node = {output};",
        f"static constexpr float maximum_correction = {literal(maximum)};",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("spec", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    result = generate(json.loads(args.spec.read_text(encoding="utf-8")))
    args.output.write_text(result, encoding="utf-8", newline="\n")
    print(args.output)


if __name__ == "__main__":
    main()
