#!/usr/bin/env python3
"""Compile the production integrator guard and RateControl using existing GTest.

No dependency installation, flight-controller connection, or uORB runtime is
performed. The real message definitions are generated by the PX4 generator.
"""

import argparse
import json
from pathlib import Path
import shlex
import subprocess
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gtest-dir", type=Path, required=True,
                        help="Existing googletest checkout root (contains googletest/src/gtest-all.cc)")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--sanitize", action="store_true", help="Enable address and undefined-behavior sanitizers")
    args = parser.parse_args()
    firmware = Path(__file__).resolve().parents[4]
    gtest = args.gtest_dir.resolve() / "googletest"
    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)
    generated = output / "generated" / "uORB" / "topics"
    binary = output / "rate_control_integrator_tests"
    commands = []

    def run(command):
        command = [str(arg) for arg in command]
        print("+ " + shlex.join(command), flush=True)
        result = subprocess.run(command, cwd=firmware, text=True, stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT)
        print(result.stdout, end="", flush=True)
        commands.append({"command": command, "returncode": result.returncode, "output": result.stdout})
        (output / "commands.json").write_text(json.dumps(commands, indent=2), encoding="utf-8")
        if result.returncode:
            raise subprocess.CalledProcessError(result.returncode, command)

    if not (gtest / "src" / "gtest-all.cc").is_file():
        parser.error("GTest source not present; this runner does not fetch or install dependencies")

    run(["g++", "--version"])
    run([sys.executable, "Tools/msg/px_generate_uorb_topic_files.py", "--headers",
         "-f", "msg/ActuatorArmed.msg", "msg/VehicleControlMode.msg", "msg/VehicleStatus.msg",
         "msg/RateCtrlStatus.msg", "-e", "Tools/msg/templates/uorb", "-o", generated])

    flags = ["-std=c++14", "-O1", "-g", "-Wall", "-Wextra", "-Werror", "-pthread",
             "-D__PX4_POSIX", "-D__EXPORT="]
    if args.sanitize:
        flags += ["-fsanitize=address,undefined", "-fno-omit-frame-pointer"]
    includes = [output / "generated", firmware / "src/modules/mc_rate_control/tests/host",
                firmware / "src", firmware / "src/lib", firmware / "src/lib/matrix", firmware / "platforms/common",
                firmware / "platforms/common/include", gtest / "include", gtest]
    run(["g++", *flags, *["-I" + str(path) for path in includes],
         firmware / "src/modules/mc_rate_control/RateControlIntegratorTest.cpp",
         firmware / "src/lib/rate_control/rate_control_test.cpp",
         firmware / "src/lib/rate_control/rate_control.cpp",
         gtest / "src/gtest-all.cc", gtest / "src/gtest_main.cc", "-o", binary])
    run([binary, "--gtest_color=no", "--gtest_output=xml:" + str(output / "results.xml")])
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except subprocess.CalledProcessError as exc:
        sys.exit(exc.returncode)
