// Generated by Tools/merivus/flight_control_research/candidate.py; do not edit.
// Candidate SHA-256: 5dd4cb06a89874fd2b995b7212dc48993df046b9aadf3b4ce3465ac2e5995281
static constexpr Node nodes[] = {
	{Op::VelocityError, -1, -1, 0.0f, 0.0f, 0.0f},
	{Op::VelocityGain, 0, -1, 0.2f, 0.2f, 0.0f},
	{Op::AccelerationResidual, -1, -1, 0.0f, 0.0f, 0.0f},
	{Op::LowpassAcceleration, 2, -1, 0.12f, 0.0f, 0.0f},
	{Op::LowpassAcceleration, 2, -1, 1.5f, 0.0f, 0.0f},
	{Op::AccelerationGain, 3, -1, -0.15f, -0.15f, 0.0f},
	{Op::AccelerationGain, 4, -1, 0.15f, 0.15f, 0.0f},
	{Op::AddAcceleration, 5, 6, 0.0f, 0.0f, 0.0f},
	{Op::AddAcceleration, 1, 7, 0.0f, 0.0f, 0.0f},
	{Op::VelocityGate, 0, 8, 0.08f, 0.25f, 0.0f},
	{Op::LimitAcceleration, 9, -1, 0.35f, 0.35f, 0.05f},
};
static constexpr unsigned node_count = 11;
static constexpr unsigned output_node = 10;
static constexpr float maximum_correction = 0.5f;
