name: MERIVUS FMUv6C Firmware

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-nuttx-focal:2021-09-08
    env:
      PX4_TARGET: px4_fmu-v6c
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
    - name: ccache cache files
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ env.PX4_TARGET }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: ${{ env.PX4_TARGET }}-ccache-
    - name: setup ccache
      run: |
          mkdir -p ~/.ccache
          echo "base_dir = ${GITHUB_WORKSPACE}" > ~/.ccache/ccache.conf
          echo "compression = true" >> ~/.ccache/ccache.conf
          echo "compression_level = 6" >> ~/.ccache/ccache.conf
          echo "max_size = 120M" >> ~/.ccache/ccache.conf
          echo "hash_dir = false" >> ~/.ccache/ccache.conf
          ccache -s
          ccache -z

    - name: Build FMUv6C firmware
      run: make ${{ env.PX4_TARGET }}_default
      timeout-minutes: 45
    - name: ccache post-run
      run: ccache -s

    - name: Upload FMUv6C package
      uses: actions/upload-artifact@v4
      with:
        name: merivus-px4_fmu-v6c
        if-no-files-found: error
        path: |
          build/px4_fmu-v6c_default/px4_fmu-v6c_default.px4
          build/px4_fmu-v6c_default/px4_fmu-v6c_default.elf
