name: MAVROS Offboard Tests

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {test_file: "mavros_posix_tests_offboard_posctl.test", vehicle: "iris", build_type: "RelWithDebInfo"}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Build PX4 and run MAVROS offboard test
      uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
      with:
        image: px4io/px4-dev-ros-melodic:2021-09-08
        options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined -v ${{ github.workspace }}:/workspace
        run: |
          cd /workspace
          git config --global --add safe.directory /workspace
          export PX4_CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
          make px4_sitl_default
          make px4_sitl_default sitl_gazebo-classic
          ./test/rostest_px4_run.sh ${{ matrix.config.test_file }} vehicle:=${{ matrix.config.vehicle }}
